### ISSUE TITLE
Full planet import fails

### ISSUE THREAD

**Issue by n3ziniuka5** [pelias/openstreetmap#394]
So I am trying to import full planet data. I am getting an error and don't know what might be the issue. Importer machine has 55GB of ram.
```
2018-02-03T16:51:30.228Z - verbose: [openstreetmap-points] openstreetmap:address:node:2526283258 5 Могилёвская улица lon=27.540751, lat=53.884583
2018-02-03T16:51:30.228Z - verbose: [openstreetmap-points] openstreetmap:venue:node:2526283258 Пивной магазин "Точка lon=27.540751, lat=53.884583
2018-02-03T16:51:30.22
npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! pelias-openstreetmap@0.0.0-semantic-release start: `node --max_old_space_size=4096 index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pelias-openstreetmap@0.0.0-semantic-release start script 'node --max_old_space_size=4096 index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pelias-openstreetmap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --max_old_space_size=4096 index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pelias-openstreetmap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pelias-openstreetmap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/geocoding/importers/openstreetmap/npm-debug.log
```

npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pelias-openstreetmap@0.0.0-semantic-release~prestart: pelias-openstreetmap@0.0.0-semantic-release
6 silly lifecycle pelias-openstreetmap@0.0.0-semantic-release~prestart: no script for prestart, continuing
7 info lifecycle pelias-openstreetmap@0.0.0-semantic-release~start: pelias-openstreetmap@0.0.0-semantic-release
8 verbose lifecycle pelias-openstreetmap@0.0.0-semantic-release~start: unsafe-perm in lifecycle true
9 verbose lifecycle pelias-openstreetmap@0.0.0-semantic-release~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/geocoding/importers/openstreetmap/node_modules/.bin:/home/geocoding/bin:/home/geocoding/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle pelias-openstreetmap@0.0.0-semantic-release~start: CWD: /home/geocoding/importers/openstreetmap
11 silly lifecycle pelias-openstreetmap@0.0.0-semantic-release~start: Args: [ '-c', 'node --max_old_space_size=4096 index.js' ]
12 silly lifecycle pelias-openstreetmap@0.0.0-semantic-release~start: Returned: code: 1  signal: null
13 info lifecycle pelias-openstreetmap@0.0.0-semantic-release~start: Failed to exec start script
14 verbose stack Error: pelias-openstreetmap@0.0.0-semantic-release start: `node --max_old_space_size=4096 index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid pelias-openstreetmap@0.0.0-semantic-release
16 verbose cwd /home/geocoding/importers/openstreetmap
17 error Linux 4.4.0-112-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error pelias-openstreetmap@0.0.0-semantic-release start: `node --max_old_space_size=4096 index.js`
22 error Exit status 1
23 error Failed at the pelias-openstreetmap@0.0.0-semantic-release start script 'node --max_old_space_size=4096 index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pelias-openstreetmap package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node --max_old_space_size=4096 index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pelias-openstreetmap
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pelias-openstreetmap
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by orangejulius** [comment]
Hey @n3ziniuka5,
This is a long shot, but I vaguely recall that we dropped support for early versions of Node.js 4. In any case it is not a good idea to run such an old version (you are on 4.2.6 which was released in January 2016).

Let me know if upgrading to at least 4.8.7 helps.

If you can, upgrade to Node.js 6 or 8. They're faster and Node.js 4 is going to stop receiving any support in a few months, so you might as well.

**Comment by n3ziniuka5** [comment]
@orangejulius 
Thanks, will try that when I can and will post the outcome here.

**Comment by n3ziniuka5** [comment]
Now getting this immediately at start:
```
> pelias-openstreetmap@0.0.0-semantic-release start /home/geocoding/importers/openstreetmap
> node --max_old_space_size=4096 index.js

2018-02-04T12:13:06.160Z - info: [openstreetmap] Creating read stream for: /mnt/data/pelias/openstreetmap/planet-latest.osm.pbf
2018-02-04T12:13:06.180Z - info: [wof-pip-service:master] starting with layers neighbourhood,borough,locality,localadmin,county,macrocounty,macroregion,region,dependency,country,empire,continent,marinearea,ocean
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
buffer.js:597
  throw new TypeError('Unknown encoding: ' + encoding);
  ^

TypeError: Unknown encoding: 
    at stringSlice (buffer.js:597:9)
    at Buffer.toString (buffer.js:633:10)
    at CSVStream.write (/home/geocoding/importers/openstreetmap/node_modules/csv-stream/index.js:59:34)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2042:12)
2018-02-04T12:13:11.428Z - verbose: [openstreetmap] [address_extractor] duplicating a venue with address
2018-02-04T12:13:11.810Z - verbose: [openstreetmap] [address_extractor] duplicating a venue with address
```

using nodejs v8.9.4.

The process didn't exit, but it is not outputting anything else.

**Comment by orangejulius** [comment]
Hey @n3ziniuka5,
My apologies, we actually hadn't merged the required changes to support Node.js 8 to this repo yet. The production branch should now be good to go, let me know what it says now.

**Comment by n3ziniuka5** [comment]
Thanks, that resolved the issue.
