### ISSUE TITLE
Error: "0" must be an object

### ISSUE THREAD

**Issue by kylebarron** [pelias/openstreetmap#408]
I wanted to start from scratch, and try to set up Pelias while writing down all my steps in a [Makefile](https://github.com/kylebarron/pelias-install). I believe I've done the same steps as before; I've downloaded the files, updated `pelias.json` and created the elasticsearch index. But I'm getting this error with `npm start` on both the master and production branches. Is there something simple I'm getting wrong?

```
> npm start

> pelias-openstreetmap@0.0.0-semantic-release start /disk/homedirs/barronk/pelias-install/openstreetmap
> node --max_old_space_size=4096 index.js

/disk/homedirs/barronk/pelias-install/openstreetmap/node_modules/pelias-config/index.js:29
      throw new Error(result.error.details[0].message);
      ^

Error: "0" must be an object
    at Object.generate (/disk/homedirs/barronk/pelias-install/openstreetmap/node_modules/pelias-config/index.js:29:13)
    at Object.<anonymous> (/disk/homedirs/barronk/pelias-install/openstreetmap/index.js:1:109)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pelias-openstreetmap@0.0.0-semantic-release start: `node --max_old_space_size=4096 index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pelias-openstreetmap@0.0.0-semantic-release start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /homes/nber/barronk/.npm/_logs/2018-04-12T22_29_24_548Z-debug.log
```

**Comment by orangejulius** [comment]
Hmm. What does `pelias.json` contain?

**Comment by kylebarron** [comment]
```
> ls /disk/agebulk1/medicare.work/doyle-DUA18266/barronk/raw/pelias/openstreetmap
us-midwest-latest.osm.pbf
us-northeast-latest.osm.pbf
us-south-latest.osm.pbf
us-west-latest.osm.pbf
```

```
{
    "elasticsearch": {
        "settings": {
            "index": {
                "number_of_replicas": 1,
                "number_of_shards": 20,
                "refresh_interval": "1m"
            }
        }
    },
    "imports": {
        "adminLookup": {
            "enabled": true
        },
        "openaddresses": {
            "datapath": "/disk/agebulk1/medicare.work/doyle-DUA18266/barronk/raw/pelias/openaddresses",
            "files": []
        },
        "openstreetmap": {
            "datapath": "/disk/agebulk1/medicare.work/doyle-DUA18266/barronk/raw/pelias/openstreetmap",
            "import": [
                "us-northeast-latest.osm.pbf",
                "us-midwest-latest.osm.pbf",
                "us-south-latest.osm.pbf",
                "us-west-latest.osm.pbf"
            ]
        },
        "polyline": {
            "datapath": "/disk/agebulk1/medicare.work/doyle-DUA18266/barronk/raw/pelias/polylines",
            "files": [
                "road_network.polylines"
            ]
        },
        "whosonfirst": {
            "datapath": "/disk/agebulk1/medicare.work/doyle-DUA18266/barronk/raw/pelias/whosonfirst",
            "importPlace": 85633793,
            "importPostalcodes": true,
            "importVenues": false
        }
    },
    "interpolation": {
        "client": {
            "adapter": "null"
        }
    }
}
```

**Comment by kylebarron** [comment]
Ah my bad

**Comment by orangejulius** [comment]
Ah, I think the issue is that each element of the "import" property in the "openstreetmap" importer has to be an object :P

**Comment by kylebarron** [comment]
Yeah I just realized that, sorry!

**Comment by orangejulius** [comment]
We do need to make better error messages, everyone on the pelias team has wasted tons of time chasing down JSON errors.

Your install script looks great, let us know how it ends up working out

**Comment by kylebarron** [comment]
It's working now!

It's my first time writing a Makefile, so it won't be elegant but hopefully it will at least rigorously record my steps.
