### ISSUE TITLE
Fatal Error in Data Mapper

### ISSUE THREAD

**Issue by missinglink** [pelias/openstreetmap#42]
```bash
if( !val ){ throw new Error( 'invalid value' ); }
                ^
Error: invalid value
    at Document.setter (/mnt/pelias/pelias-osm/releases/20150317234057/node_modules/pelias-model/util/model.js:56:23)
    at Document.setLat (/mnt/pelias/pelias-osm/releases/20150317234057/node_modules/pelias-model/Document.js:136:16)
    at Document.setCentroid (/mnt/pelias/pelias-osm/releases/20150317234057/node_modules/pelias-model/Document.js:146:15)
    at DestroyableTransform._transform (/mnt/pelias/pelias-osm/releases/20150317234057/stream/document_constructor.js:18:11)
    at DestroyableTransform.Transform._read (/mnt/pelias/pelias-osm/releases/20150317234057/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Readable.read (/mnt/pelias/pelias-osm/releases/20150317234057/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:362:10)
    at flow (/mnt/pelias/pelias-osm/releases/20150317234057/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:629:52)
    at DestroyableTransform.<anonymous> (/mnt/pelias/pelias-osm/releases/20150317234057/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:613:7)
    at DestroyableTransform.emit (events.js:92:17)
    at onwriteDrain (/mnt/pelias/pelias-osm/releases/20150317234057/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:300:12)
    at afterWrite (/mnt/pelias/pelias-osm/releases/20150317234057/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:288:5)
```

reported by @heffergm

**Comment by missinglink** [comment]
related: https://github.com/pelias/model/pull/11

**Comment by missinglink** [comment]
this issue is caused by a bug with zero lat/lon values, it's solved in the PR linked above and requires that to be merged in order to prevent a regression.

I have a local feature branch containing `try/catch` code in order to avoid the fatal nature of the error but it will require the above to be merged and published before I can open a PR on this repo.

**Comment by missinglink** [comment]
```bash
$ npm publish
+ pelias-openstreetmap@1.1.0
```
