### ISSUE TITLE
Unexpected name tags

### ISSUE THREAD

**Issue by missinglink** [pelias/openstreetmap#44]
```bash
error constructing document model Error: invalid property
    at Document.setter [as setName] (/mnt/pelias/pelias-osm/releases/20150318110004/node_modules/pelias-model/util/model.js:54:24)
    at DestroyableTransform._transform (/mnt/pelias/pelias-osm/releases/20150318110004/stream/tag_mapper.js:34:17)
    at DestroyableTransform.Transform._read (/mnt/pelias/pelias-osm/releases/20150318110004/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/mnt/pelias/pelias-osm/releases/20150318110004/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/mnt/pelias/pelias-osm/releases/20150318110004/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/mnt/pelias/pelias-osm/releases/20150318110004/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/mnt/pelias/pelias-osm/releases/20150318110004/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/mnt/pelias/pelias-osm/releases/20150318110004/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/mnt/pelias/pelias-osm/releases/20150318110004/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/mnt/pelias/pelias-osm/releases/20150318110004/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (/mnt/pelias/pelias-osm/releases/20150318110004/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/mnt/pelias/pelias-osm/releases/20150318110004/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
```

reported by @heffergm

**Comment by missinglink** [comment]
this is related to the wide variety of name tags [1], in developement

[1] http://taginfo.openstreetmap.org/search?q=name%3A

**Comment by missinglink** [comment]
This specific issue was caused by an extraneous colon and resolved in https://github.com/pelias/openstreetmap/pull/45

```bash
{ 'name:': 'foo' }
       ^
```
