### ISSUE TITLE
issue while executing npm start cmd

### ISSUE THREAD

**Issue by sachinuengage** [pelias/openstreetmap#575]
![image](https://github.com/pelias/openstreetmap/assets/145963205/2cffeafd-0c17-46a9-9722-62ca92e72949)

**Comment by timothy-barus** [comment]
I think you missing to add path whosonfirst or check permission on your folder /tmp

```
"whosonfirst": {
      "datapath": "/mnt/pelias/whosonfirst",
      "importPostalcodes": true
    }
```

**Comment by raphael10-collab** [comment]
Hi @timothy-barus 
I'm experiencing the same issue

this is the pelias.json file : 
    
    (base) root@WorldMap:~# cat pelias.json 
    {
      "interpolation": {
        "client": {
          "adapter": "http",
          "host": "http://localhost:9999"
        }
      },
      "imports": {
        "geonames": {
          "datapath": "/media/hdd/geonames",
          "import": [{
            "filename": "allCountries.txt"
          }]
        },
        "openstreetmap": {
          "datapath": "/media/hdd/osm",
          "import": [{
            "filename": "planet-latest.osm.pbf"
          }]
        },
        "openaddresses": {
          "datapath": "/media/hdd/openaddresses",
          "files": [
            "global.csv"
          ]
        },
        "polyline": {
          "datapath": "~/polyline",
          "files": [
            "road_network.polylines"
          ]
        },
        "whosonfirst": {
          "datapath": "/media/hdd/whosonfirst",
          "importPostalcodes": true
        }
      }
    }



    (base) root@WorldMap:~# ls -lah /media/hdd/whosonfirst/
    total 69G
    drwxr-xr-x 2 root root 4.0K May 21 09:50 .
    drwxr-xr-x 6 root root 4.0K May 23 09:21 ..
    -rw-r--r-- 1 root root  40G May  6 17:17 whosonfirst-data-admin-latest.db
    -rw-r--r-- 1 root root 631M May  6 17:08 whosonfirst-data-constituency-latest.db
    -rw-r--r-- 1 root root  29G May  6 17:16 whosonfirst-data-postalcode-latest.db
    (base) root@WorldMap:~# 


    (base) root@WorldMap:~# sqlite3 --version
    3.45.3 2024-04-15 13:34:05 8653b758870e6ef0c98d46b3ace27849054af85da891eb121e9aaa537f1e8355 (64-bit)
    
    (base) root@WorldMap:~# node --version
    v22.14.0
    
    OS: Ubuntu 24.04

What am I missing and/or doing wrong?
How to make it work?

**Comment by arnesetzer** [comment]
As mentioned in https://github.com/pelias/whosonfirst/issues/555 
the files should be in `whosonfirstFolder/sqlite/data.db` and **not** in `whosonfirstFolder/data.db`. If that is not the case you will get the error message. 
To fix this `cd data/whosonfirst && mkdir -p sqlite && mv *.db sqlite/`

**Comment by raphael10-collab** [comment]
@arnesetzer Sorry for bothering you again but this time I created an empty sqlite3 db in /whosonfirst/sqlite/ folder but it says "no database found" : 
    
    raphy@WorldMap:~/pelias/data_world/whosonfirst/sqlite$ sqlite3 whosonfirst.db "VACUUM;"
    raphy@WorldMap:~/pelias/data_world/whosonfirst/sqlite$ ls -lah
    total 12K
    drwxrwxr-x 2 raphy raphy 4.0K Jun 18 18:10 .
    drwxrwxr-x 3 raphy raphy 4.0K Jun 18 17:59 ..
    -rw-r--r-- 1 raphy raphy 4.0K Jun 18 18:10 whosonfirst.db




    raphy@WorldMap:~/pelias/whosonfirst$ npm start
    
    > pelias-whosonfirst@0.0.0-development start
    > ./bin/start
    
    /home/raphy/pelias/whosonfirst/import.js:19
        throw (_.isError(err) ? err : new Error(err));
        ^
    
    Error: No database found in /home/raphy/pelias/data_world/whosonfirst/sqlite
        at /home/raphy/pelias/whosonfirst/import.js:19:35
        at getDBList (/home/raphy/pelias/whosonfirst/src/bundleList.js:54:12)
        at Object.getList [as generateBundleList] (/home/raphy/pelias/whosonfirst/src/bundleList.js:61:12)
        at Object.<anonymous> (/home/raphy/pelias/whosonfirst/import.js:16:9)
        at Module._compile (node:internal/modules/cjs/loader:1356:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
        at Module.load (node:internal/modules/cjs/loader:1197:32)
        at Module._load (node:internal/modules/cjs/loader:1013:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
        at node:internal/main/run_main_module:28:49
    
    Node.js v18.19.1
